### PR TITLE
fix : tailwind.config.ts and home page

### PR DESCRIPTION
**Pull request by Harshil-0707**
I have added the necessary code to tailwind.config.ts to enable all pages using custom Tailwind CSS to access the new styles. Additionally, I removed some unused commented lines.

### CODE REVIEW

**Comment by Harshil-0707** [comment]
I don't know typescript so I cannot add functionality at the present time.

**Comment by Harshil-0707** [comment]
So when are you going to merge branch?

**Comment by slashexx** [comment]
> I don't know typescript so I cannot add functionality at the present time.

@Harshil-0707 No worries about that. I suggested a change (put `package-lock.json` in .gitignore) btw, I'll merge as soon as you commit it.

We don't really need `package-lock.json` usually.

**Comment by Harshil-0707** [comment]
Ok

**Comment by Harshil-0707** [comment]
package-lock.json is already in the .gitignore file.

**Comment by slashexx** [comment]
> package-lock.json is already in the .gitignore file. 

Ah my bad, it seems there's a typo in .gitignore. Kindly put `package-lock.json` instead of `package.lock.json`. Apologies for troubling about this nit.

https://github.com/Nexusrex18/lumine/blob/226f205d06f378293743fe51302e3ae122a170de/project/.gitignore

**Comment by Harshil-0707** [comment]
Fixed!

**Comment by slashexx** [comment]
> Fixed!

Thanks for working on this ❤️ 

LGTM !

**Comment by Harshil-0707** [comment]
Your welcome 😊

**Pull request merged**
